/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ru.alexey_ovcharov.rusfootballmanager.represent;

import ru.alexey_ovcharov.rusfootballmanager.entities.player.Player;
import ru.alexey_ovcharov.rusfootballmanager.entities.team.Team;

import javax.swing.*;
import java.util.List;

/**
 * @author Алексей
 */
public class TeamSettingsForm extends javax.swing.JDialog {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bFromMainToSub;
    private javax.swing.JButton bFromReserveToSub;
    private javax.swing.JButton bFromSubToMain;
    private javax.swing.JButton bFromSubToReserve;
    private javax.swing.JButton bSaveAndExit;
    private javax.swing.JComboBox<String> cbFreeKick;
    private javax.swing.JComboBox<String> cbLeftCorner;
    private javax.swing.JComboBox<String> cbPenalty;
    private javax.swing.JComboBox<String> cbRightCorner;
    private javax.swing.JComboBox<String> cbStyle;
    private javax.swing.JComboBox<String> cbTactic;
    private javax.swing.JCheckBox chBreakthroughAndFeed;
    private javax.swing.JCheckBox chEarlySubstitutions;
    private javax.swing.JCheckBox chMinorFault;
    private javax.swing.JCheckBox chPowerSaving;
    private javax.swing.JCheckBox chSafety;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lFreeKick;
    private javax.swing.JLabel lLeftCorner;
    private javax.swing.JLabel lMainPlayers;
    private javax.swing.JLabel lPenalty;
    private javax.swing.JLabel lReservePlayers;
    private javax.swing.JLabel lRightCorner;
    private javax.swing.JLabel lStyle;
    private javax.swing.JLabel lSubstitutes;
    private javax.swing.JLabel lTactic;
    private javax.swing.JList<String> listStartPlayers;
    private javax.swing.JList<String> listReservePlayers;
    private javax.swing.JList<String> listSubstitutes;

    private Team team;

    /**
     * Creates new form TeamSettingsForm
     */
    public TeamSettingsForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setTeam(Team team) {
        this.team = team;
        List<Player> startPlayers = team.getStartPlayers();
        listStartPlayers.setModel(new PlayersListModel(startPlayers));

        List<Player> substitutes = team.getSubstitutes();
        listSubstitutes.setModel(new PlayersListModel(substitutes));

        List<Player> reserve = team.getReserve();
        listSubstitutes.setModel(new PlayersListModel(reserve));

        listStartPlayers.updateUI();
        listSubstitutes.updateUI();
        listReservePlayers.updateUI();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listStartPlayers = new javax.swing.JList<>();
        lMainPlayers = new javax.swing.JLabel();
        lSubstitutes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSubstitutes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listReservePlayers = new javax.swing.JList<>();
        lReservePlayers = new javax.swing.JLabel();
        cbTactic = new javax.swing.JComboBox<>();
        lTactic = new javax.swing.JLabel();
        lStyle = new javax.swing.JLabel();
        cbStyle = new javax.swing.JComboBox<>();
        chMinorFault = new javax.swing.JCheckBox();
        chSafety = new javax.swing.JCheckBox();
        chPowerSaving = new javax.swing.JCheckBox();
        chEarlySubstitutions = new javax.swing.JCheckBox();
        chBreakthroughAndFeed = new javax.swing.JCheckBox();
        cbPenalty = new javax.swing.JComboBox<>();
        lPenalty = new javax.swing.JLabel();
        lFreeKick = new javax.swing.JLabel();
        cbFreeKick = new javax.swing.JComboBox<>();
        lRightCorner = new javax.swing.JLabel();
        cbRightCorner = new javax.swing.JComboBox<>();
        lLeftCorner = new javax.swing.JLabel();
        cbLeftCorner = new javax.swing.JComboBox<>();
        bSaveAndExit = new javax.swing.JButton();
        bFromSubToMain = new javax.swing.JButton();
        bFromSubToReserve = new javax.swing.JButton();
        bFromMainToSub = new javax.swing.JButton();
        bFromReserveToSub = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listStartPlayers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listStartPlayers);

        lMainPlayers.setText("Основной состав");

        lSubstitutes.setText("Запасные");

        listSubstitutes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listSubstitutes);

        listReservePlayers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listReservePlayers);

        lReservePlayers.setText("Резерв");

        cbTactic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"4-4-2", "4-2-2-2", "4-1-4-1", "4-1-2-1-2", "4-3-3", "4-5-1", "3-5-2", "3-4-3", "3-2-3-2", "5-4-1", "5-3-2", "5-1-3-1"}));

        lTactic.setText("Тактика");

        lStyle.setText("Стиль");

        cbStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Плотная оборона", "Оборона", "Баланс", "Атака", "Рискованная атака"}));

        chMinorFault.setText("Мелкий фол");
        chMinorFault.setToolTipText("Мелкий фол может помочь против техничных команд");

        chSafety.setText("Подстраховка");
        chSafety.setToolTipText("Подстраховка снижает шанс пропустить, но увеличивает расход сил");

        chPowerSaving.setText("Экономия сил");
        chPowerSaving.setToolTipText("Экономит силы за счет меньшего подключения к атакам защитников, меньше шанс забить гол");

        chEarlySubstitutions.setText("Ранние замены");
        chEarlySubstitutions.setToolTipText("Позволяют балансировать силы, но могут снизить сыгранность и затрудняю маневры");

        chBreakthroughAndFeed.setText("Прорыв и подача");
        chBreakthroughAndFeed.setToolTipText("Заставляет крайних защитников и полузащитников предпочитать навес попыткам прорыва");

        lPenalty.setText("Бьет пенальти");

        lFreeKick.setText("Бьет штрафной удар");

        lRightCorner.setText("Правый угловой");

        lLeftCorner.setText("Левый угловой");

        bSaveAndExit.setText("Сохранить и выйти");
        bSaveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveAndExitActionPerformed(evt);
            }
        });

        bFromSubToMain.setText("<");
        bFromSubToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFromSubToMainActionPerformed(evt);
            }
        });

        bFromSubToReserve.setText(">");
        bFromSubToReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFromSubToReserveActionPerformed(evt);
            }
        });

        bFromMainToSub.setText(">");
        bFromMainToSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFromMainToSubActionPerformed(evt);
            }
        });

        bFromReserveToSub.setText("<");
        bFromReserveToSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFromReserveToSubActionPerformed(evt);
            }
        });

        bCancel.setText("Отмена");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                      .add(layout.createSequentialGroup()
                                 .addContainerGap()
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                       .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                  .add(lMainPlayers)
                                                                  .add(lTactic)
                                                                  .add(lStyle)
                                                                  .add(layout.createSequentialGroup()
                                                                             .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, cbStyle, 0, 230, Short.MAX_VALUE)
                                                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, cbTactic, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                                                             .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                                             .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                                        .add(bFromMainToSub)
                                                                                        .add(bFromSubToMain))))
                                                       .add(18, 18, 18)
                                                       .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                  .add(layout.createSequentialGroup()
                                                                             .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                                                        .add(layout.createSequentialGroup()
                                                                                                   .add(lRightCorner)
                                                                                                   .add(142, 142, 142))
                                                                                        .add(cbPenalty, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                        .add(cbRightCorner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                        .add(org.jdesktop.layout.GroupLayout.LEADING, lSubstitutes)
                                                                                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                                             .add(10, 10, 10)
                                                                             .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                                        .add(bFromSubToReserve)
                                                                                        .add(bFromReserveToSub)))
                                                                  .add(lPenalty))
                                                       .add(18, 18, 18)
                                                       .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                  .add(lReservePlayers)
                                                                  .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                  .add(cbFreeKick, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                  .add(lFreeKick)
                                                                  .add(lLeftCorner)
                                                                  .add(cbLeftCorner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 225, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                  .add(layout.createSequentialGroup()
                                                                             .add(bCancel)
                                                                             .add(18, 18, 18)
                                                                             .add(bSaveAndExit))))
                                            .add(layout.createSequentialGroup()
                                                       .add(chMinorFault)
                                                       .add(18, 18, 18)
                                                       .add(chSafety)
                                                       .add(18, 18, 18)
                                                       .add(chPowerSaving)
                                                       .add(18, 18, 18)
                                                       .add(chEarlySubstitutions)
                                                       .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                       .add(chBreakthroughAndFeed)))
                                 .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                      .add(layout.createSequentialGroup()
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                       .add(15, 15, 15)
                                                       .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                                  .add(lMainPlayers)
                                                                  .add(lSubstitutes)))
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                                                                                 .addContainerGap()
                                                                                                 .add(lReservePlayers)))
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                       .add(18, 18, 18)
                                                       .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 325, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(layout.createSequentialGroup()
                                                       .add(68, 68, 68)
                                                       .add(bFromSubToReserve)
                                                       .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                       .add(bFromReserveToSub))
                                            .add(layout.createSequentialGroup()
                                                       .add(66, 66, 66)
                                                       .add(bFromMainToSub)
                                                       .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                       .add(bFromSubToMain))
                                            .add(layout.createSequentialGroup()
                                                       .add(18, 18, 18)
                                                       .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                  .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 325, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                  .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 325, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                 .add(11, 11, 11)
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(lTactic)
                                            .add(lPenalty)
                                            .add(lFreeKick))
                                 .add(8, 8, 8)
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(cbTactic, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cbPenalty, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cbFreeKick, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                 .add(18, 18, 18)
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(lStyle)
                                            .add(lRightCorner)
                                            .add(lLeftCorner))
                                 .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(cbStyle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cbRightCorner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cbLeftCorner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                 .add(26, 26, 26)
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                            .add(chMinorFault)
                                            .add(chSafety)
                                            .add(chPowerSaving)
                                            .add(chEarlySubstitutions)
                                            .add(chBreakthroughAndFeed)
                                            .add(bCancel)
                                            .add(bSaveAndExit))
                                 .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFromMainToSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFromMainToSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFromMainToSubActionPerformed

    private void bFromSubToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFromSubToMainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFromSubToMainActionPerformed

    private void bFromSubToReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFromSubToReserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFromSubToReserveActionPerformed

    private void bFromReserveToSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFromReserveToSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFromReserveToSubActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveAndExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSaveAndExitActionPerformed


    private static class PlayersListModel extends AbstractListModel<String> {
        private final List<Player> players;

        PlayersListModel(List<Player> players) {
            this.players = players;
        }

        @Override
        public int getSize() {
            return players.size();
        }

        @Override
        public String getElementAt(int index) {
            Player player = players.get(index);
            return player.getNameAbbrAndLastName() + " " + player.getAverage();
        }
    }

    // End of variables declaration//GEN-END:variables

}
